### ISSUE TITLE
Test failing due to the incorrect solution filename

### ISSUE THREAD

**Issue by olegggatttor** [RareSkills/zero-knowledge-puzzles#16]
`MultiplyNoOut.js` test uses an incorrect solution filename.

`const circuit = await wasm_tester(path.join(__dirname,"../MultiplyNoOutput/","MultiplyNoOutput.circom"));`

should be changed to

`const circuit = await wasm_tester(path.join(__dirname,"../MultiplyNoOut/","MultiplyNoOut.circom"));`

**Comment by RareSkills** [comment]
Fixed with merged PR https://github.com/RareSkills/zero-knowledge-puzzles/pull/26
