### ISSUE TITLE
`sudoku.circom` is not capitalized, test file cannot find circuit.

### ISSUE THREAD

**Issue by calvbore** [RareSkills/zero-knowledge-puzzles#6]
https://github.com/RareSkills/zero-knowledge-puzzles/blob/1d8d766f65a3a54443015956f01e0eadc01c2d34/test/Sudoku.js#L20
`sudoku.circom` is not capitalized, test file cannot find circuit.

should be renamed to `Sudoku.circom`

#4 deals with this.

**Comment by supernovahs** [comment]
Merged
