### ISSUE TITLE
Error with `script.sh` while generating `verifier.sol` contract inside `..\contracts` dir

### ISSUE THREAD

**Issue by mmsaki** [RareSkills/zero-knowledge-puzzles#7]
Line 53 [snarkjs zkey export solidityverifier Mul_0001.zkey ../contracts/verifier.sol](https://github.com/RareSkills/zero-knowledge-puzzles/blob/1d8d766f65a3a54443015956f01e0eadc01c2d34/Compile/script.sh#L53-L54)

Changes can either be:
- `mdkir ../contracts/` before creating verifier contract 
- or using `snarkjs zkey export solidityverifier Mul_0001.zkey verifier.sol` for the contracts to be on same directory

**Comment by tanim0la** [comment]
Merged PR #26 already addressed this issue
